#!/bin/bash
cd $(dirname $0)/../..

export WORKON_HOME=$(pwd)

source $(which virtualenvwrapper.sh)
if [ $? != 0 ]
then
  echo "Missing prerequisite virtualenvwrapper, bailing out"
  exit 1
fi

if (! test -d "$WORKON_HOME/.spotifylib")
then
  echo "Creating virtual env for .spotifylib"
  mkvirtualenv ".spotifylib"
fi

echo "Working on virtualenv spotifylib"
source "$WORKON_HOME/.spotifylib/bin/activate"

echo "Installing python package requirements.."
pip install -r requirements.txt
